/**
 * UK station CRS codes lookup.
 * Static embedded map of Network Rail station codes — no external API calls.
 * Each CRS code appears exactly once.
 */

const stationData: ReadonlyArray<readonly [string, string]> = [
  // === London Terminals ===
  ["KGX", "London Kings Cross"],
  ["STP", "London St Pancras"],
  ["PAD", "London Paddington"],
  ["VIC", "London Victoria"],
  ["WAT", "London Waterloo"],
  ["LST", "London Liverpool Street"],
  ["EUS", "London Euston"],
  ["CHX", "London Charing Cross"],
  ["LBG", "London Bridge"],
  ["FST", "London Fenchurch Street"],
  ["MYB", "London Marylebone"],
  ["BFR", "London Blackfriars"],
  ["CST", "London Cannon Street"],
  ["WAE", "London Waterloo East"],
  ["CTK", "City Thameslink"],
  ["SFA", "London St Pancras International"],
  ["ZFD", "London St Pancras Low Level"],

  // === London Suburban ===
  ["CLJ", "Clapham Junction"],
  ["SRA", "Stratford (London)"],
  ["ECR", "East Croydon"],
  ["WCY", "West Croydon"],
  ["FPK", "Finsbury Park"],
  ["HGY", "Hornsey"],
  ["AXR", "Alexandra Palace"],
  ["OLD", "Old Street"],
  ["MHM", "Moorgate"],
  ["KTN", "Kensington Olympia"],
  ["SPB", "Shepherd's Bush"],
  ["ACT", "Acton Main Line"],
  ["EAL", "Ealing Broadway"],
  ["SOU", "Southall"],
  ["HNW", "Hanwell"],
  ["HAY", "Hayes & Harlington"],
  ["WDT", "West Drayton"],
  ["IVR", "Iver"],
  ["LNB", "Langley (Berks)"],
  ["BNH", "Burnham (Bucks)"],
  ["SLO", "Slough"],
  ["MAI", "Maidenhead"],
  ["TAP", "Taplow"],
  ["TWY", "Twyford"],
  ["ABW", "Abbey Wood"],
  ["CUS", "Custom House"],
  ["TOM", "Tottenham Hale"],
  ["SVS", "Seven Sisters"],
  ["BHO", "Blackhorse Road"],
  ["WLT", "Walthamstow Central"],
  ["CHF", "Cheshunt"],
  ["BXB", "Broxbourne"],
  ["HWC", "Hertford East"],
  ["HFN", "Hertford North"],
  ["ENF", "Enfield Town"],
  ["EDT", "Edmonton Green"],
  ["HRW", "Harrow-on-the-Hill"],
  ["WEA", "Wembley Stadium"],
  ["HEN", "Hendon"],
  ["MIL", "Mill Hill Broadway"],
  ["ELS", "Elstree & Borehamwood"],
  ["RAD", "Radlett"],
  ["BKG", "Barking"],
  ["UPM", "Upminster"],
  ["RMF", "Romford"],
  ["GDH", "Goodmayes"],
  ["SNF", "Shenfield"],
  ["BAT", "Battersea Park"],
  ["PUT", "Putney"],
  ["WIM", "Wimbledon"],
  ["RAY", "Raynes Park"],
  ["SUR", "Surbiton"],
  ["TWI", "Twickenham"],
  ["RMD", "Richmond"],
  ["SNL", "Stoneleigh"],
  ["EWE", "Ewell East"],
  ["EPH", "Epsom"],
  ["CYP", "Crystal Palace"],
  ["NWD", "Norwood Junction"],
  ["ANZ", "Anerley"],
  ["PGE", "Penge East"],
  ["WDO", "West Dulwich"],
  ["SYD", "Sydenham"],
  ["FNR", "Forest Hill"],
  ["HNH", "Honor Oak Park"],
  ["BKR", "Brockley"],
  ["NXG", "New Cross Gate"],
  ["NWX", "New Cross"],
  ["DPT", "Deptford"],
  ["GNW", "Greenwich"],
  ["MGN", "Maze Hill"],
  ["WEH", "Westcombe Park"],
  ["CHR", "Charlton"],
  ["KDB", "Kidbrooke"],
  ["BKL", "Blackheath"],
  ["LGN", "Lewisham"],
  ["HTE", "Hither Green"],
  ["GRP", "Grove Park"],
  ["SBR", "Sundridge Park"],
  ["BKJ", "Bromley North"],
  ["BMS", "Bromley South"],
  ["PET", "Petts Wood"],
  ["CHG", "Chislehurst"],
  ["ELM", "Elmstead Woods"],
  ["MOT", "Mottingham"],
  ["NED", "New Eltham"],
  ["SDC", "Sidcup"],
  ["ABI", "Albany Park"],
  ["BXY", "Bexley"],
  ["CRY", "Crayford"],
  ["SDE", "Slade Green"],
  ["DAR", "Dartford"],
  ["SWM", "Swanscombe"],
  ["NFL", "Northfleet"],
  ["GRV", "Gravesend"],
  ["HSG", "Higham"],
  ["SOO", "Strood"],
  ["ORP", "Orpington"],
  ["CTN", "Catford"],
  ["CTF", "Catford Bridge"],
  ["BEK", "Beckenham Junction"],
  ["ELW", "Elmers End"],
  ["EDN", "Eden Park"],

  // === Airports ===
  ["STN", "Stansted Airport"],
  ["LGW", "Gatwick Airport"],
  ["LTN", "Luton Airport Parkway"],
  ["BHI", "Birmingham International"],
  ["MIA", "Manchester Airport"],
  ["SOA", "Southampton Airport Parkway"],
  ["PEA", "Prestwick International Airport"],

  // === Major Cities ===
  ["MAN", "Manchester Piccadilly"],
  ["MCO", "Manchester Oxford Road"],
  ["MCV", "Manchester Victoria"],
  ["BHM", "Birmingham New Street"],
  ["LDS", "Leeds"],
  ["SHF", "Sheffield"],
  ["LIV", "Liverpool Lime Street"],
  ["LPY", "Liverpool South Parkway"],
  ["NCL", "Newcastle"],
  ["BRI", "Bristol Temple Meads"],
  ["EDB", "Edinburgh Waverley"],
  ["GLC", "Glasgow Central"],
  ["GLQ", "Glasgow Queen Street"],
  ["CDF", "Cardiff Central"],
  ["NRW", "Norwich"],
  ["NOT", "Nottingham"],
  ["OXF", "Oxford"],
  ["CBG", "Cambridge"],
  ["YRK", "York"],
  ["PLY", "Plymouth"],
  ["SOT", "Southampton Central"],
  ["RDG", "Reading"],
  ["PBO", "Peterborough"],
  ["DHM", "Durham"],
  ["DON", "Doncaster"],
  ["CRE", "Crewe"],

  // === South East England ===
  ["ASH", "Ashford International"],
  ["CBW", "Canterbury West"],
  ["CBE", "Canterbury East"],
  ["DVP", "Dover Priory"],
  ["FKS", "Folkestone Central"],
  ["FKW", "Folkestone West"],
  ["GIL", "Gillingham (Kent)"],
  ["RTR", "Rochester"],
  ["CHT", "Chatham"],
  ["CHM", "Chelmsford"],
  ["COL", "Colchester"],
  ["IPS", "Ipswich"],
  ["GLD", "Guildford"],
  ["WOK", "Woking"],
  ["WIN", "Winchester"],
  ["HAS", "Hastings"],
  ["EBN", "Eastbourne"],
  ["BRH", "Brighton"],
  ["WRH", "Worthing"],
  ["BOG", "Bognor Regis"],
  ["CHI", "Chichester"],
  ["PMH", "Portsmouth Harbour"],
  ["PMS", "Portsmouth & Southsea"],
  ["FRM", "Fareham"],
  ["HAV", "Havant"],
  ["TBD", "Tunbridge Wells"],
  ["TON", "Tonbridge"],
  ["SEV", "Sevenoaks"],
  ["LHD", "Leatherhead"],
  ["DKG", "Dorking"],
  ["RDH", "Redhill"],
  ["HOR", "Horsham"],
  ["CWD", "Crawley"],
  ["TBW", "Three Bridges"],
  ["HYS", "Haywards Heath"],
  ["LWS", "Lewes"],
  ["SNR", "Sanderstead"],
  ["SLQ", "St Leonards Warrior Square"],
  ["ORE", "Ore"],
  ["RYE", "Rye"],
  ["MTG", "Margate"],
  ["RAM", "Ramsgate"],
  ["HVN", "Herne Bay"],
  ["WHI", "Whitstable"],
  ["FAV", "Faversham"],
  ["SIT", "Sittingbourne"],
  ["SWL", "Swale"],
  ["SNW", "Sheerness-on-Sea"],
  ["PDW", "Paddock Wood"],
  ["CGR", "Charing (Kent)"],
  ["BEX", "Bexhill"],
  ["MSR", "Maidstone East"],
  ["MDW", "Maidstone West"],
  ["EGR", "East Grinstead"],
  ["OXD", "Oxted"],
  ["UWL", "Upper Warlingham"],
  ["HIB", "Hildenborough"],
  ["YAL", "Yalding"],
  ["WHN", "Wateringbury"],
  ["BRN", "Barming"],
  ["EML", "East Malling"],
  ["WMA", "West Malling"],
  ["BRR", "Borough Green & Wrotham"],
  ["OTF", "Otford"],
  ["BBL", "Bat & Ball"],
  ["KMS", "Kemsing"],
  ["EBR", "Edenbridge"],
  ["EBT", "Edenbridge Town"],
  ["HEV", "Hever"],
  ["COH", "Cowden"],
  ["AHS", "Ashurst"],
  ["FRN", "Frant"],

  // === Herts / Beds / Bucks ===
  ["WFJ", "Watford Junction"],
  ["SAC", "St Albans City"],
  ["HFP", "Harpenden"],
  ["LUT", "Luton"],
  ["BEE", "Bedford"],
  ["HML", "Hemel Hempstead"],
  ["BKM", "Berkhamsted"],
  ["TRI", "Tring"],
  ["LBZ", "Leighton Buzzard"],
  ["BLY", "Bletchley"],
  ["MKC", "Milton Keynes Central"],
  ["WOL", "Wolverton"],
  ["SVG", "Stevenage"],
  ["HIT", "Hitchin"],
  ["LET", "Letchworth Garden City"],
  ["BDK", "Baldock"],
  ["ASG", "Ashwell & Morden"],
  ["RYS", "Royston"],
  ["MEL", "Meldreth"],
  ["SHY", "Shepreth"],
  ["FOX", "Foxton"],
  ["KNB", "Knebworth"],
  ["WGC", "Welwyn Garden City"],
  ["WLG", "Welwyn North"],
  ["HAT", "Hatfield"],
  ["BRX", "Brookmans Park"],
  ["POT", "Potters Bar"],
  ["ARL", "Arlesey"],
  ["BIW", "Biggleswade"],
  ["SDY", "Sandy"],
  ["SNO", "St Neots"],
  ["HUN", "Huntingdon"],
  ["BIS", "Bishops Stortford"],
  ["HWN", "Harlow Town"],

  // === East Anglia ===
  ["DIS", "Diss"],
  ["SMK", "Stowmarket"],
  ["MNG", "Manningtree"],
  ["WIC", "Wickford"],
  ["SSD", "Southend Victoria"],
  ["SOC", "Southend Central"],
  ["SOE", "Southend East"],
  ["SOF", "Southminster"],
  ["FEN", "Felixstowe"],
  ["WDB", "Woodbridge"],
  ["SAX", "Saxmundham"],
  ["LOF", "Lowestoft"],
  ["GSY", "Great Yarmouth"],
  ["CRF", "Cromer"],
  ["SHM", "Sheringham"],
  ["KLN", "Kings Lynn"],
  ["DOW", "Downham Market"],
  ["ELY", "Ely"],
  ["MCH", "March"],
  ["AUR", "Audley End"],
  ["BRT", "Braintree"],
  ["WTM", "Witham"],
  ["CLT", "Clacton-on-Sea"],
  ["WON", "Walton-on-the-Naze"],
  ["HRH", "Harwich Town"],
  ["HPQ", "Harwich International"],
  ["THD", "Thetford"],
  ["ATL", "Attleborough"],
  ["WMD", "Wymondham"],
  ["SLR", "Salhouse"],
  ["WXH", "Wroxham"],
  ["NWA", "North Walsham"],

  // === Berkshire / Wiltshire ===
  ["RDW", "Reading West"],
  ["TIL", "Tilehurst"],
  ["THE", "Theale"],
  ["MDG", "Midgham"],
  ["THA", "Thatcham"],
  ["NBY", "Newbury"],
  ["KWB", "Kintbury"],
  ["HGR", "Hungerford"],
  ["BWR", "Bedwyn"],
  ["PEW", "Pewsey"],

  // === South West England ===
  ["EXD", "Exeter St Davids"],
  ["EXC", "Exeter Central"],
  ["NTA", "Newton Abbot"],
  ["TQY", "Torquay"],
  ["PAI", "Paignton"],
  ["TRU", "Truro"],
  ["PNZ", "Penzance"],
  ["TAU", "Taunton"],
  ["WSM", "Weston-super-Mare"],
  ["BPW", "Bristol Parkway"],
  ["BTH", "Bath Spa"],
  ["FRO", "Frome"],
  ["WSB", "Westbury"],
  ["WMN", "Warminster"],
  ["YVJ", "Yeovil Junction"],
  ["YVP", "Yeovil Pen Mill"],
  ["SWI", "Swindon"],
  ["DID", "Didcot Parkway"],
  ["BAN", "Banbury"],
  ["BMH", "Bournemouth"],
  ["POO", "Poole"],
  ["WEY", "Weymouth"],
  ["DOR", "Dorchester South"],
  ["DCW", "Dorchester West"],
  ["AXM", "Axminster"],
  ["HNL", "Honiton"],
  ["CKN", "Crewkerne"],
  ["SBE", "Sherborne"],
  ["GCR", "Gloucester"],
  ["CNM", "Cheltenham Spa"],
  ["CPM", "Chippenham"],
  ["KBL", "Kemble"],
  ["STD", "Stroud"],
  ["STO", "Stonehouse"],
  ["SAL", "Salisbury"],
  ["CSA", "Castle Cary"],
  ["FNC", "Feniton"],
  ["WHM", "Whimple"],
  ["PIN", "Pinhoe"],
  ["TEI", "Teignmouth"],
  ["DWS", "Dawlish"],
  ["DWW", "Dawlish Warren"],
  ["SXS", "Starcross"],
  ["EXM", "Exmouth"],
  ["LYP", "Lympstone Village"],
  ["CRD", "Crediton"],
  ["EGG", "Eggesford"],
  ["UMP", "Umberleigh"],
  ["BNT", "Barnstaple"],
  ["IVY", "Ivybridge"],
  ["TOT", "Totnes"],

  // === Cornwall ===
  ["LSK", "Liskeard"],
  ["BDM", "Bodmin Parkway"],
  ["LOS", "Lostwithiel"],
  ["PAR", "Par"],
  ["SAU", "St Austell"],
  ["RED", "Redruth"],
  ["CPW", "Camborne"],
  ["HYL", "Hayle"],
  ["SER", "St Erth"],
  ["SIV", "St Ives"],
  ["FMR", "Falmouth Docks"],
  ["FMT", "Falmouth Town"],
  ["PNM", "Penryn"],
  ["PRW", "Perranwell"],
  ["NQY", "Newquay"],

  // === Hampshire & Dorset ===
  ["BSK", "Basingstoke"],
  ["OVR", "Overton"],
  ["WCH", "Whitchurch (Hampshire)"],
  ["AND", "Andover"],
  ["GRT", "Grateley"],
  ["BSL", "Bruton"],

  // === Sussex (additional) ===
  ["PLD", "Portslade"],
  ["FIS", "Fishersgate"],
  ["SSG", "Southwick"],
  ["SHA", "Shoreham-by-Sea"],
  ["LAN", "Lancing"],
  ["GOR", "Goring-by-Sea"],
  ["ANG", "Angmering"],
  ["FBN", "Ford (Sussex)"],
  ["LHA", "Littlehampton"],
  ["ARU", "Arundel"],
  ["AMB", "Amberley"],
  ["PUL", "Pulborough"],
  ["BLL", "Billingshurst"],
  ["CHS", "Christ's Hospital"],
  ["LIT", "Littlehaven"],
  ["FAY", "Faygate"],
  ["IFI", "Ifield"],
  ["BUG", "Burgess Hill"],
  ["HSK", "Hassocks"],
  ["PRP", "Preston Park"],

  // === East Midlands ===
  ["NNG", "Newark North Gate"],
  ["NNT", "Newark Castle"],
  ["GRA", "Grantham"],
  ["LBO", "Loughborough"],
  ["LEI", "Leicester"],
  ["RUG", "Rugby"],
  ["COV", "Coventry"],
  ["NMP", "Northampton"],
  ["KET", "Kettering"],
  ["WEL", "Wellingborough"],
  ["COR", "Corby"],
  ["MHR", "Market Harborough"],
  ["EMD", "East Midlands Parkway"],
  ["DBY", "Derby"],
  ["BUJ", "Burton-on-Trent"],
  ["TAM", "Tamworth"],
  ["LTV", "Lichfield Trent Valley"],
  ["CNG", "Chesterfield"],
  ["ALF", "Alfreton"],
  ["LGE", "Langley Mill"],
  ["ILK", "Ilkeston"],
  ["BEV", "Beeston"],
  ["ATB", "Attenborough"],
  ["MAT", "Matlock"],
  ["MTB", "Matlock Bath"],
  ["CMF", "Cromford"],

  // === West Midlands ===
  ["BMO", "Birmingham Moor Street"],
  ["BSW", "Birmingham Snow Hill"],
  ["WVH", "Wolverhampton"],
  ["WSR", "Walsall"],
  ["DDY", "Dudley Port"],
  ["SBJ", "Stourbridge Junction"],
  ["KDM", "Kidderminster"],
  ["WOS", "Worcester Shrub Hill"],
  ["WOF", "Worcester Foregate Street"],
  ["MLV", "Malvern Link"],
  ["GMV", "Great Malvern"],
  ["TFC", "Telford Central"],
  ["SHR", "Shrewsbury"],
  ["NUN", "Nuneaton"],
  ["ATO", "Atherstone"],
  ["HNB", "Hinckley"],
  ["SOL", "Solihull"],
  ["DDG", "Dorridge"],
  ["WRW", "Warwick"],
  ["WRP", "Warwick Parkway"],
  ["LMS", "Leamington Spa"],
  ["SAV", "Stratford-upon-Avon"],
  ["STA", "Stafford"],
  ["SOK", "Stoke-on-Trent"],
  ["ALG", "Alsager"],
  ["KDS", "Kidsgrove"],
  ["MAC", "Macclesfield"],
  ["CNS", "Congleton"],

  // === Yorkshire & Humber ===
  ["HUL", "Hull"],
  ["HUD", "Huddersfield"],
  ["WKF", "Wakefield Westgate"],
  ["WKK", "Wakefield Kirkgate"],
  ["BDI", "Bradford Interchange"],
  ["BDQ", "Bradford Forster Square"],
  ["HFX", "Halifax"],
  ["DEW", "Dewsbury"],
  ["BTY", "Batley"],
  ["MIR", "Mirfield"],
  ["SKT", "Skipton"],
  ["KGT", "Keighley"],
  ["ILY", "Ilkley"],
  ["HRG", "Harrogate"],
  ["KNA", "Knaresborough"],
  ["SEL", "Selby"],
  ["THI", "Thirsk"],
  ["NTH", "Northallerton"],
  ["DLM", "Darlington"],
  ["MBR", "Middlesbrough"],
  ["RCC", "Redcar Central"],
  ["SCR", "Scarborough"],
  ["MLT", "Malton"],
  ["FIL", "Filey"],
  ["BDT", "Bridlington"],
  ["BEF", "Beverley"],
  ["GOO", "Goole"],
  ["HBP", "Horsforth"],
  ["GUY", "Guiseley"],
  ["MEN", "Menston"],
  ["BYW", "Burley-in-Wharfedale"],
  ["CAS", "Castleford"],
  ["PFR", "Pontefract Monkhill"],
  ["KNO", "Knottingley"],
  ["SHL", "Shipley"],
  ["SAE", "Saltaire"],
  ["BIY", "Bingley"],
  ["HCR", "Horton-in-Ribblesdale"],
  ["SET", "Settle"],
  ["APB", "Appleby"],
  ["LAZ", "Lazonby & Kirkoswald"],
  ["PNR", "Penrith"],
  ["MHS", "Meadowhall"],
  ["ROT", "Rotherham Central"],
  ["MEX", "Mexborough"],
  ["CLN", "Cleethorpes"],
  ["GMB", "Grimsby Town"],
  ["SCU", "Scunthorpe"],
  ["BAR", "Barnsley"],
  ["PNS", "Penistone"],

  // === North West England ===
  ["LVC", "Liverpool Central"],
  ["BON", "Bolton"],
  ["RCD", "Rochdale"],
  ["OLM", "Oldham Mumps"],
  ["WGN", "Wigan North Western"],
  ["WGW", "Wigan Wallgate"],
  ["PRE", "Preston"],
  ["BPN", "Blackpool North"],
  ["BPS", "Blackpool South"],
  ["BPB", "Blackpool Pleasure Beach"],
  ["BBN", "Blackburn"],
  ["BYM", "Burnley Manchester Road"],
  ["ACC", "Accrington"],
  ["LAC", "Lancaster"],
  ["OXN", "Oxenholme Lake District"],
  ["WDM", "Windermere"],
  ["KEN", "Kendal"],
  ["CRL", "Carlisle"],
  ["WKG", "Workington"],
  ["WTH", "Whitehaven"],
  ["MRY", "Maryport"],
  ["BSB", "Barrow-in-Furness"],
  ["ULV", "Ulverston"],
  ["GRG", "Grange-over-Sands"],
  ["CNF", "Carnforth"],
  ["MBE", "Morecambe"],
  ["CHE", "Chester"],
  ["SPT", "Stockport"],
  ["ALT", "Altrincham"],
  ["SLE", "Sale"],
  ["NAV", "Navigation Road"],
  ["BNY", "Burnage"],
  ["MLD", "Mauldeth Road"],
  ["LVM", "Levenshulme"],
  ["HEA", "Heaton Chapel"],
  ["APN", "Appley Bridge"],
  ["GST", "Gathurst"],
  ["OMS", "Ormskirk"],
  ["WID", "Widnes"],
  ["RUN", "Runcorn"],
  ["RUE", "Runcorn East"],
  ["ELP", "Ellesmere Port"],
  ["WAR", "Warrington Central"],
  ["WBQ", "Warrington Bank Quay"],
  ["NTG", "Northwich"],
  ["HTF", "Hartford"],
  ["CLH", "Clitheroe"],
  ["WHL", "Whalley"],
  ["LGO", "Langho"],
  ["RIS", "Rishton"],
  ["CHU", "Church & Oswaldtwistle"],
  ["HCT", "Huncoat"],
  ["RSS", "Rose Hill Marple"],
  ["RML", "Romiley"],
  ["BDY", "Bredbury"],
  ["WNR", "Woodsmoor"],
  ["DAV", "Davenport"],
  ["CHD", "Cheadle Hulme"],
  ["BNA", "Bramhall"],
  ["POY", "Poynton"],
  ["ADC", "Adlington (Cheshire)"],
  ["MRF", "Marple"],
  ["NSG", "New Mills Newtown"],
  ["NMC", "New Mills Central"],
  ["BXN", "Buxton"],

  // === North East England ===
  ["SMD", "Sunderland"],
  ["HRT", "Hartlepool"],
  ["HEX", "Hexham"],
  ["HTW", "Haltwhistle"],
  ["MPT", "Morpeth"],
  ["ALM", "Alnmouth"],
  ["BEW", "Berwick-upon-Tweed"],
  ["MCE", "MetroCentre"],
  ["BLO", "Blaydon"],
  ["CLS", "Chester-le-Street"],
  ["NWC", "Newton Aycliffe"],
  ["BIA", "Bishop Auckland"],

  // === Trans-Pennine ===
  ["HDL", "Hebden Bridge"],
  ["TOD", "Todmorden"],
  ["LTL", "Littleborough"],
  ["MIH", "Mills Hill"],
  ["MOS", "Moston"],
  ["ASN", "Ashton-under-Lyne"],
  ["SYB", "Stalybridge"],
  ["GLS", "Glossop"],
  ["HDF", "Hadfield"],
  ["HPE", "Hope (Derbyshire)"],
  ["EDA", "Edale"],
  ["GRN", "Grindleford"],
  ["DHN", "Dore & Totley"],
  ["NHY", "New Hey"],

  // === Chiltern Line ===
  ["SPR", "South Ruislip"],
  ["DEN", "Denham"],
  ["GER", "Gerrards Cross"],
  ["SRG", "Seer Green"],
  ["BCF", "Beaconsfield"],
  ["HPD", "High Wycombe"],
  ["SND", "Saunderton"],
  ["PRR", "Princes Risborough"],
  ["HDM", "Haddenham & Thame Parkway"],
  ["BCS", "Bicester North"],

  // === Scotland ===
  ["EDP", "Edinburgh Park"],
  ["HYM", "Haymarket"],
  ["ABD", "Aberdeen"],
  ["DEE", "Dundee"],
  ["INV", "Inverness"],
  ["PTH", "Perth"],
  ["STL", "Stirling"],
  ["FKK", "Falkirk High"],
  ["FKG", "Falkirk Grahamston"],
  ["LKG", "Linlithgow"],
  ["KDY", "Kirkcaldy"],
  ["INK", "Inverkeithing"],
  ["DFL", "Dunfermline Town"],
  ["DAG", "Dunfermline Queen Margaret"],
  ["DFE", "Dunfermline City"],
  ["AYR", "Ayr"],
  ["KMK", "Kilmarnock"],
  ["PSC", "Paisley Gilmour Street"],
  ["PTK", "Partick"],
  ["MTH", "Motherwell"],
  ["HMY", "Hamilton Central"],
  ["LGS", "Larkhall"],
  ["CUH", "Cumbernauld"],
  ["GRK", "Greenock Central"],
  ["WMS", "Wemyss Bay"],
  ["LAG", "Largs"],
  ["ADS", "Ardrossan South Beach"],
  ["LEU", "Leuchars"],
  ["CPR", "Cupar"],
  ["LDY", "Ladybank"],
  ["MNC", "Markinch"],
  ["GLT", "Glenrothes with Thornton"],
  ["DAM", "Dalmeny"],
  ["NQU", "North Queensferry"],
  ["NBW", "North Berwick"],
  ["DUN", "Dunbar"],
  ["RSY", "Rosyth"],
  ["PKT", "Polmont"],
  ["AVA", "Aviemore"],
  ["KGU", "Kingussie"],
  ["NWR", "Newtonmore"],
  ["PIT", "Pitlochry"],
  ["BLA", "Blair Atholl"],
  ["DAW", "Dalwhinnie"],
  ["CRA", "Crianlarich"],
  ["UPT", "Upper Tyndrum"],
  ["BEA", "Bridge of Allan"],
  ["ALO", "Alloa"],
  ["ADR", "Airdrie"],
  ["BHG", "Bathgate"],
  ["LVN", "Livingston North"],
  ["LVS", "Livingston South"],
  ["OBN", "Oban"],
  ["FTW", "Fort William"],
  ["MLG", "Mallaig"],
  ["KYL", "Kyle of Lochalsh"],
  ["DGW", "Dingwall"],
  ["TAI", "Tain"],
  ["ARG", "Ardgay"],
  ["LAI", "Lairg"],
  ["GOL", "Golspie"],
  ["BRA", "Brora"],
  ["HMS", "Helmsdale"],
  ["WCK", "Wick"],
  ["TRS", "Thurso"],
  ["SNN", "Stonehaven"],
  ["MTS", "Montrose"],
  ["ARB", "Arbroath"],
  ["CRN", "Carnoustie"],
  ["BYF", "Broughty Ferry"],
  ["MFI", "Monifieth"],
  ["DMF", "Dumfries"],
  ["ANS", "Annan"],
  ["GEA", "Gretna Green"],
  ["LOC", "Lockerbie"],
  ["CAR", "Carstairs"],
  ["COT", "Coatbridge Central"],
  ["COS", "Coatbridge Sunnyside"],
  ["BLH", "Bellshill"],
  ["HLC", "Helensburgh Central"],
  ["HLU", "Helensburgh Upper"],
  ["BAD", "Balloch"],
  ["DBC", "Dumbarton Central"],
  ["DAC", "Dalmuir"],
  ["CYK", "Clydebank"],
  ["MLN", "Milngavie"],
  ["BRD", "Bearsden"],
  ["WES", "Westerton"],
  ["ANL", "Anniesland"],
  ["BTG", "Bridge of Allan"],

  // === Wales ===
  ["CDQ", "Cardiff Queen Street"],
  ["SWA", "Swansea"],
  ["NPT", "Newport (South Wales)"],
  ["WRX", "Wrexham General"],
  ["WXC", "Wrexham Central"],
  ["ABH", "Aberystwyth"],
  ["MCY", "Machynlleth"],
  ["NWT", "Newtown (Powys)"],
  ["WLP", "Welshpool"],
  ["PWL", "Pwllheli"],
  ["POR", "Porthmadog"],
  ["CRG", "Criccieth"],
  ["BFL", "Barmouth"],
  ["TYW", "Tywyn"],
  ["ABV", "Aberdovey"],
  ["BOH", "Borth"],
  ["LWR", "Llanwrtyd"],
  ["LLW", "Llandrindod"],
  ["KNI", "Knighton"],
  ["BUK", "Builth Road"],
  ["LDV", "Llandovery"],
  ["LLE", "Llanelli"],
  ["FGW", "Fishguard & Goodwick"],
  ["PTA", "Port Talbot Parkway"],
  ["NEA", "Neath"],
  ["CMN", "Carmarthen"],
  ["HHD", "Holyhead"],
  ["AGV", "Abergavenny"],
  ["HFD", "Hereford"],
  ["FLN", "Flint"],
  ["TFF", "Llandaf"],
  ["RHL", "Rhyl"],
  ["PRT", "Prestatyn"],
  ["CLL", "Colwyn Bay"],
  ["LJN", "Llandudno Junction"],
  ["LLN", "Llandudno"],
  ["BNG", "Bangor (Gwynedd)"],
  ["ABA", "Aberdare"],
  ["MER", "Merthyr Tydfil"],
  ["TRH", "Treherbert"],
  ["PON", "Pontypool & New Inn"],
  ["CYS", "Caerphilly"],
  ["BGN", "Bargoed"],
  ["RHY", "Rhymney"],
  ["PYC", "Pontypridd"],
  ["BYI", "Barry Island"],
  ["BYD", "Barry Docks"],
  ["MLF", "Milford Haven"],
  ["PMB", "Pembroke"],
  ["PMD", "Pembroke Dock"],

  // === Cumbria Coast ===
  ["WGT", "Wigton"],
  ["ASP", "Aspatria"],
  ["FLM", "Flimby"],
  ["HRN", "Harrington"],
  ["PTN", "Parton"],
  ["CTW", "Corkickle"],
  ["STB", "St Bees"],
  ["NET", "Nethertown"],
  ["BYS", "Braystones"],
  ["SLF", "Sellafield"],
  ["SCS", "Seascale"],
  ["DRG", "Drigg"],
  ["RAV", "Ravenglass"],
  ["BOO", "Bootle (Cumbria)"],
  ["SIL", "Silecroft"],
  ["MLM", "Millom"],
  ["GNR", "Green Road"],
  ["FOD", "Foxfield"],
  ["KBF", "Kirkby-in-Furness"],
  ["ASK", "Askam"],
  ["DAT", "Dalton"],
  ["ROO", "Roose"],

  // === East Coast Main Line (additional) ===
  ["RET", "Retford"],
  ["DBG", "Dunbar"],

  // === Nottinghamshire ===
  ["MSD", "Mansfield"],
  ["MFT", "Mansfield Woodhouse"],
  ["SRB", "Shirebrook"],
  ["WKS", "Worksop"],
  ["SRK", "Shireoaks"],
  ["CWL", "Creswell"],

  // === Additional stations for comprehensive coverage ===
  ["NFD", "Northfield"],
  ["WLN", "Willington"],
  ["RDR", "Redbridge"],
  ["HUP", "Hull Paragon"],

  // More Scottish stations
  ["TAY", "Tayport"],
  ["TCN", "Troon"],
  ["PTW", "Prestwick Town"],
  ["GFN", "Girvan"],
  ["STR", "Stranraer"],
  ["KBK", "Kilwinning"],
  ["DRM", "Drumgelloch"],
  ["CKT", "Coatdyke"],
  ["SBT", "Shotts"],
  ["FWM", "Fauldhouse"],
  ["ADW", "Addiewell"],
  ["WCL", "West Calder"],
  ["MXW", "Midcalder"],
  ["CRK", "Curriehill"],
  ["KGE", "Kingsknowe"],
  ["SHT", "Slateford"],
  ["WBF", "Wester Hailes"],
  ["EDG", "Edinburgh Gateway"],

  // Additional English stations
  ["ACK", "Acklington"],
  ["CBR", "Camberley"],
  ["FNY", "Finchley Road & Frognal"],
  ["GPO", "Gospel Oak"],
  ["KSN", "Kentish Town"],
  ["WHP", "West Hampstead"],
  ["BRK", "Brookwood"],
  ["AHV", "Ash Vale"],
  ["ASI", "Ash"],
  ["WNS", "Wanstead Park"],
  ["PDG", "Pudding Mill Lane"],
  ["HKW", "Hackney Wick"],
  ["HMT", "Homerton"],
  ["HKC", "Hackney Central"],
  ["DLK", "Dalston Kingsland"],
  ["CNN", "Canonbury"],
  ["HOH", "Highbury & Islington"],
  ["CMD", "Camden Road"],
  ["KTW", "Kentish Town West"],
  ["SOH", "South Hampstead"],
  ["KQP", "Kilburn High Road"],
  ["BSO", "Brondesbury"],
  ["BSP", "Brondesbury Park"],
  ["KNR", "Kensal Rise"],
  ["WIJ", "Willesden Junction"],
  ["ACL", "Acton Central"],
  ["SKW", "South Acton"],
  ["GNH", "Gunnersbury"],
  ["KEW", "Kew Gardens"],

  // More Midlands
  ["LIC", "Lichfield City"],
  ["TYS", "Tyseley"],
  ["OHL", "Olton"],
  ["WDI", "Widney Manor"],
  ["LPW", "Lapworth"],
  ["HTN", "Hatton"],
];

export const STATIONS: ReadonlyMap<string, string> = new Map(stationData);

export function getStationName(crs: string): string | undefined {
  return STATIONS.get(crs.toUpperCase());
}

export function findStation(
  query: string,
): Array<{ crs: string; name: string }> {
  const lowerQuery = query.toLowerCase();
  const matches: Array<{ crs: string; name: string }> = [];

  for (const [crs, name] of STATIONS) {
    if (name.toLowerCase().includes(lowerQuery)) {
      matches.push({ crs, name });
    }
  }

  return matches.sort((a, b) => a.name.localeCompare(b.name)).slice(0, 10);
}

export function isValidCrs(crs: string): boolean {
  return STATIONS.has(crs.toUpperCase());
}
